config/routes.rb
Rails.application.routes.draw do
  resources :wechats

end

app/models/token.rb
class Token < ActiveRecord::Base
  def self.get_access_token
    if Token.where(:id=>1).first == nil
      Token.init_access_token
    end

    if Time.now - Token.where(id: 1).first.update_time > 7190
      token_access = Token.refresh_access_token
    else
      token_access = Token.where(:id=>1).first.access_token
    end
  end

  def self.refresh_access_token
    token = Token.where(:id=>1).first
    link = "https://api.weixin.qq.com/cgi-bin/token?grant_type=client_credential&appid=#{token.appid}&secret=#{token.appsecret}"
    token.access_token = JSON.parse(RestClient.get(link))["access_token"]
    token.update_time = Time.now
    token.save
  end
  
  def self.init_access_token
    if Token.where(:id=>1).first == nil
      token = Token.new
      token.appid = "wx02f639cfd30b9a3b"
      token.appsecret = "110bc5b5b33257ae3098bfddb8170a11"
      token.update_time = "2015-08-01 11:30:55 +0800"
      token.access_token = "KyDTZFAb8fx4S5zsW9KaCXXI_ViKjXQN2lM0CxsvDkBL6UdSbBdw3P9zuByxM4h5A335A54zw9p0-U8_F-FLKWClPrXF43Tc7CzIEabVYh0"
      token.save
    end
  end
end

app/models/wechat.rb
class Wechat < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/wechats_controller.rb
class WechatsController < ApplicationController
  before_action :set_wechat, only: [:show, :edit, :update, :destroy]

  # GET /wechats
  # GET /wechats.json
  def index
    @wechats = Wechat.all
     logger.info "----------------"
    logger.info "<xml>
    <ToUserName><![CDATA[#{params["xml"]["FromUserName"]}]]></ToUserName>
    <FromUserName><![CDATA[#{params["xml"]["ToUserName"]}]]></FromUserName>
    <CreateTime>#{Time.now.to_i}</CreateTime>
    <MsgType><![CDATA[text]]></MsgType>
    <Content><![CDATA[你好]]></Content>
    </xml>"
    # unless params[:echostr].blank?
    #   token = 'weixin'

    #   timestamp = params[:timestamp]
    #   nonce = params[:nonce]
    #   echostr = params[:echostr]
    #   signature = params[:signature]

    #   aray =  [token, timestamp, nonce].sort
    #   tmp = ""
    #   aray.each do |s|
    #     tmp += s  
    #   end
    #   tmp = Digest::SHA1.hexdigest(tmp)

    #   logger.info "---#{echostr}-------#{tmp == signature}----------"
    #   if tmp == signature 
    #     render :text => echostr
    #   else 
    #     render :text => ""
    #   end
    # end
  end

  # GET /wechats/1
  # GET /wechats/1.json
  def show
  end

  # GET /wechats/new
  def new
    @wechat = Wechat.new
  end

  # GET /wechats/1/edit
  def edit
  end

  # POST /wechats
  # POST /wechats.json
  def create
    @wechat = Wechat.new(wechat_params)

    respond_to do |format|
      if @wechat.save
        format.html { redirect_to @wechat, notice: 'Wechat was successfully created.' }
        format.json { render :show, status: :created, location: @wechat }
      else
        format.html { render :new }
        format.json { render json: @wechat.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /wechats/1
  # PATCH/PUT /wechats/1.json
  def update
    respond_to do |format|
      if @wechat.update(wechat_params)
        format.html { redirect_to @wechat, notice: 'Wechat was successfully updated.' }
        format.json { render :show, status: :ok, location: @wechat }
      else
        format.html { render :edit }
        format.json { render json: @wechat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wechats/1
  # DELETE /wechats/1.json
  def destroy
    @wechat.destroy
    respond_to do |format|
      format.html { redirect_to wechats_url, notice: 'Wechat was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_wechat
      @wechat = Wechat.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def wechat_params
      params[:wechat]
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/wechats_helper.rb
module WechatsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Peizhi</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/wechats/_form.html.erb
<%= form_for(@wechat) do |f| %>
  <% if @wechat.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@wechat.errors.count, "error") %> prohibited this wechat from being saved:</h2>

      <ul>
      <% @wechat.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/wechats/edit.html.erb
<h1>Editing Wechat</h1>

<%= render 'form' %>

<%= link_to 'Show', @wechat %> |
<%= link_to 'Back', wechats_path %>

app/views/wechats/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Wechats</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @wechats.each do |wechat| %>
      <tr>
        <td><%= link_to 'Show', wechat %></td>
        <td><%= link_to 'Edit', edit_wechat_path(wechat) %></td>
        <td><%= link_to 'Destroy', wechat, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Wechat', new_wechat_path %>

app/views/wechats/new.html.erb
<h1>New Wechat</h1>

<%= render 'form' %>

<%= link_to 'Back', wechats_path %>

app/views/wechats/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_wechat_path(@wechat) %> |
<%= link_to 'Back', wechats_path %>